### PR TITLE
Python 3.5.x Compatibility

### PR DESCRIPTION
**Pull request by Aareon**
https://github.com/Devoxin/Lavalink.py/issues/7

### CODE REVIEW

**Comment by Devoxin** [comment]
This is fixed in the master branch, awaiting @atiwiex's update for that branch

**Comment by Aareon** [comment]
This is an update for the `pip-install` branch. At least to fix this issue.

**Comment by Devoxin** [comment]
I'll wait for William's input on this just in case he may have breaking commits pending.

**Comment by Aareon** [comment]
@atiwiex

**Comment by atiwiex** [comment]
@aareon already pushed to pip

**Pull request closed without merging**
