### PR TITLE
replaces some dict accesses with get()

### PR DESCRIPTION
**Pull request by redmoogle**
### Checks and guidelines:

* [x] Have you checked that there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked that only **single quotes** are used in the code, apart from the doc-strings?
* [x] Have you run a lint program on your code prior to submission?
* [x] Have you checked if `python run_tests.py` returns no errors?

Tests output: [link](https://hastebin.com/share/wumovilono.sql)

### Type of change

* [ ] Bug fix
* [ ] New feature
* [x] Improvement
* [ ] Breaking change
* [ ] This change is a documentation update

### Describe the changes:
Use get instead of direct access and add some guard clauses to reduce to average number of exceptions by `0`

might be better to use exceptions/log.warn for the new messages

### CODE REVIEW

**Comment by redmoogle** [comment]
less likely to get tripped up over bad data

**Comment by redmoogle** [comment]
> I don't see why it should. If Lavalink is sending bad data, I don't believe it's the responsibility of the client to protect against that (in this case, anyway). That would indicate a bigger issue.

Isnt handling exceptions slower?

**Comment by Devoxin** [comment]
- If `state` is missing, player becomes semi-useless in that you can't accurately keep track of player position amongst other variables.
- If `guildId` doesn't exist, the server is broken or sending malformed data. `guildId` should never not exist.
- `op` should always exist because this is how the client knows how to handle data.

If your server is sending any data without any of the relevant fields, that would indicate a server problem. This should __never__ happen.

Given the above, plus the fact the state of this PR is messed up (and this repo has had bad experiences with messed up PRs breaking branch compatibility in the past), I'll be closing this.

**Comment by Devoxin** [comment]
> > I don't see why it should. If Lavalink is sending bad data, I don't believe it's the responsibility of the client to protect against that (in this case, anyway). That would indicate a bigger issue.
> 
> Isnt handling exceptions slower?

Also Python's entire ethos is built around EAFP, "easier to ask forgiveness than permission"

**Pull request closed without merging**
