### PR TITLE
Move static _event_hooks to an instance variable.

### PR DESCRIPTION
**Pull request by burtonwilliamt**
Having a module level function changing static variables on concrete classes (`lavalink.add_event_hook()` changing `Client._event_hooks`) feels like an anti pattern. In this PR I'm suggesting we remove as much global state as possible to clean that up.

To preserve backwards compatibility the module level `add_event_hook()` still adds event hooks to all existing `Client` instances. This is accomplished through a static `_instances` list on the `Client` class. If the maintainers are amenable, I'd suggest we instead scrap the module level function altogether, and make everything instance-specific. Baring that, I think this PR is a good middle ground. It preserves the global functionality while minimizing the global state.

This change also has the added benefits of centralizing the event hook logic in one place (lavalink.add_event_hook() just calls each instance's .add_event_hook()) as well as expanding the power of Client.add_event_hook to accept multiple hooks, and allows specifying an event type.

### Checks and guidelines:

* [x] Have you checked that there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked that only **single quotes** are used in the code, apart from the doc-strings?
* [x] Have you run a lint program on your code prior to submission?
* [x] Have you checked if `python run_tests.py` returns no errors?

Tests output: [link](https://hastebin.com/raw/uwewuhugul) 

### Type of change

* [ ] Bug fix
* [ ] New feature
* [x] Improvement
* [x] Breaking change
* [ ] This change is a documentation update

### Describe the changes:

- Consolidated the add_event_hook implementations into the Client class.
- Expanded the functionality of `Client.add_event_hook()` to take multiple hooks and optionally specify an event.
- Individual `Client` instances can have different hooks (by calling `.add_event_hook()` on the specific instance). This is useful if two discord bots are running in the same python environment.
- Removed the static `_event_hooks` list from `Client`. This is a breaking change. Any code that previously used `Client._event_hooks` will break. Additionally, the global `lavalink.add_event_hook()` will affect already constructed Clients. Clients constructed after that will not have the hooks. This is different behavior from before but I think it's unlikely any code was depending on that.

### CODE REVIEW

**Comment by Devoxin** [comment]
Any update on this?

**Comment by burtonwilliamt** [comment]
Sorry I got busy with holiday things.

Is this change something you'd be amenable to? If so, what more should I do before merge?

**Comment by Devoxin** [comment]
> Is this change something you'd be amenable to?
Yes

> If so, what more should I do before merge?
Everything looks good so far, however one thing that occurred to me is that this may be considered a breaking change for anyone who calls `lavalink.add_event_hook` before instantiating a client. With this change, clients will no longer be able to 'retroactively' detect registered event hooks prior to instantiation. As a result, this may be something better suited to v5, or perhaps even v4.1 (simply because v5 may be a long ways off).

**Comment by burtonwilliamt** [comment]
Yeah, I tried to highlight that in the last bullet point under "Describe the changes". It's also a breaking change for anyone that depended on `_event_hooks` but that might not be as big of a deal because that's marked as internal (leading _).

Waiting for 4.1 sounds good to me. Do you have an opinion around the idea of just scrapping the module-level .add_event_hook() all-together in favor of per-instance? It seems to me that the module-level is slightly more confusing, it's already duplicated code today, and I'm not sure I see the value it's adding other than being backwards compatible.

**Comment by Devoxin** [comment]
Sorry for the late update on this, I would say scrap the module-level `add_event_hook` as its behaviour is definitely confusing, event hook should always explicitly be assigned to a client. I can't really remember the original reason for adding it but with version 5.0 looming I feel it'd make sense to get rid of it entirely.

**Comment by burtonwilliamt** [comment]
Awesome, I removed the module-level add_event_hook. Sorry for the messy commits. When upstream branch became 5.0 I wasn't really sure the right way to sync all those changes. LMK if something is broken due to those merges/force pushes.

Also I looked for documentation to change and found the .rst but should I put the breaking change in a changelog somewhere?

**Comment by burtonwilliamt** [comment]
Just looking this over again, I'm not really sure why the static code analysis failed. When I click into it, it just says "diff failed" and the retry button tells me to try again later.

Is it known to be flaky and should I just ignore it? Or maybe I'm holding it wrong?

**Comment by Devoxin** [comment]
I think it's just flaky tbh. It doesn't specifically state anything is wrong.

**Comment by burtonwilliamt** [comment]
AFAIK this is ready to merge then. LMK if there's anything else I should do.

**Pull request merged**
