### PR TITLE
Infinite reconn option

### PR DESCRIPTION
**Pull request by AndyTempel**
### Checks and guidelines:

* [x] Have you checked that there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Have you checked that only **single quotes** are used in the code, apart from the doc-strings?
* [ ] Have you run a lint program on your code prior to submission?
* [x] Have you checked if `python run_tests.py` returns no errors?

Tests output: [link](https://hastebin.com/wuyuxocapu.py) 

### Type of change

* [ ] Bug fix
* [x] New feature
* [x] Improvement
* [ ] Breaking change
* [ ] This change is a documentation update

### Describe the changes:

- added option for infinite reconnects or custom reconnect attempts
- optimized imports and refactor

### CODE REVIEW

**Comment by Devoxin** [comment]
Did you by any chance base this off master?

**Comment by AndyTempel** [comment]
> Did you by any chance base this off master?

dev

**Comment by Devoxin** [comment]
hmm, what's with these extra commits

**Comment by AndyTempel** [comment]
> hmm, what's with these extra commits
> 

Idk maybe I've pulled it from master, but that shouldn't matter lmao, since it got merged with dev recently

**Pull request merged**
