### PR TITLE
Fix VOICE_SERVER_UPDATE events

### PR DESCRIPTION
**Pull request by CarlGroth**
Makes it so that you can change voice regions without the player going quiet

I ran run_tests.py and it passed both linters.

Been using this for my own bot without any problems for about a month

### CODE REVIEW

**Comment by Zenrac** [comment]
Related to #44

**Comment by AndyTempel** [comment]
Is there a way that `sessionId` could be carried over to the wrong voice ws? Or, are sessionIds per bot and not per VC.

Because that could be a problem.

**Comment by Devoxin** [comment]
`I ran run_tests.py and it passed both linters.`

Wew, linty boi

**Comment by Devoxin** [comment]
Perhaps session_ids could be stored in players (if they exist, make the var a part of the base player) so this won't affect other sessions?

**Comment by AndyTempel** [comment]
hmm could be possible, currently, I'm storing them in a dictionary with guild ID as a key and voice_state dict as a value.

**Comment by Devoxin** [comment]
Thanks for your PR! Unfortunately the suggested change would need to cover multiple guilds rather than just the one. Another PR has since been merged which I believe fixes this, and will be making its way into a public release soon.

**Pull request closed without merging**
