### PR TITLE
Converted .format() functions to new f-strings

### PR DESCRIPTION
**Pull request by sh0tx420**
### Checks and guidelines:

* [x] Have you checked that there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked that only **single quotes** are used in the code, apart from the doc-strings?
* [x] Have you run a lint program on your code prior to submission?
* [x] Have you checked if `python run_tests.py` returns no errors?
       ^- Yes and no, read notes for clarification.

Tests output: [link](https://mystb.in/GregMonteAssure.lua) 

### Type of change

* [ ] Bug fix
* [ ] New feature
* [x] Improvement
* [ ] Breaking change
* [ ] This change is a documentation update

### Describe the changes:

- I replaced the slow format() functions and replaced them with f-strings.
  f-strings, new to Python 3, are much faster than using the old format() functions used in Python 2.
  Sources:
  - https://hackernoon.com/a-closer-look-at-how-python-f-strings-work-f197736b3bdb
  - https://medium.com/@gusgoulart/python-f-strings-fun-strings-fast-strings-beeae4ddd1a
  - https://www.scivision.dev/python-f-string-speed/
  
  It is true that format() is backwards-compatible with Python 3.5 and older, but based on this badge: [Python](https://www.python.org) in README.MD, Lavalink.py does not support Python versions older than 3.6. Because of that, it's much better to switch to f-strings, again, because format() is old.

### Notes
- In [`client.py`](https://github.com/sh0tx420/Lavalink.py/blob/master/lavalink/client.py) lines 336 and 344, I had to use (example) -> `'string text %s', code` because the pylint test told me to use .format() or %s. Google says it's faster to use %s than to use .format().
- run_tests.py -> `lavalink\datarw.py:59:26: E741 ambiguous variable name 'l'` - This file has not been modified by me at all and this pull request does not aim to fix this error given by the flake8 test in `run_tests.py`.

### CODE REVIEW

**Review by waydealphax — COMMENTED** [review]
breaks python3.6

**Comment by waydealphax** [comment]
3.5

**Comment by sh0tx420** [comment]
yes

**Comment by Devoxin** [comment]
No. Would rather keep the 3.5 support.

**Comment by sh0tx420** [comment]
bruh

**Pull request closed without merging**
